### ISSUE TITLE
Make plugins work with `Plugin DSL`

### ISSUE THREAD

**Issue by wzieba** [Automattic/publish-to-s3-gradle-plugin#22]
### Context

As stated in `README.md`:

> Unfortunately, we are currently unable to utilize the Plugin DSL due to [this Gradle issue](https://github.com/gradle/gradle/issues/8754) (...) Since S3 returns 403 status code for nonexistent files, the build results in failure.

And I confirm this, using Plugin DSL for applying e.g. `publish-to-s3-gradle-plugin` gives me the same build failure.

I've done some experiments on [my test S3 bucket](https://maventests.s3.eu-central-1.amazonaws.com/) - I've published a plugin to local maven and pushed artifacts to the bucket and I got the same result (crashing build).

### Solution

It seems, that Gradle breaks build while receiving `403` but **does not when receiving `404` response code**.

To change the response code in S3 for non-existing files to `404` we could edit settings under the ACL section and allow for `Objects List` to `Everyone`. I'm not an expert in security but this does not seem to be a security breach.

#### Samples

<img width="1114" alt="image" src="https://user-images.githubusercontent.com/5845095/121195468-ea22b400-c86f-11eb-988a-04a2792ed576.png">

```
❯ curl -I https://maventests.s3.eu-central-1.amazonaws.com/com/automattic/android/publish-library-to-s3/com.automattic.android.publish-library-to-s3.gradle.plugin/0.4.1/com.automattic.android.publish-library-to-s3.gradle.plugin-0.4.1.jar
HTTP/1.1 403 Forbidden
x-amz-request-id: FBPE5GDFSVYSCSKY
x-amz-id-2: TiKdO2fa3j4ZKj/xvz18FEdzvHSKijgjustKLPlt9hH/Lh3n3yHTRTXIPgdj96NgaITfKV4YEzc=
Content-Type: application/xml
Date: Tue, 08 Jun 2021 13:40:46 GMT
Server: AmazonS3
```

---

<img width="1117" alt="image" src="https://user-images.githubusercontent.com/5845095/121195349-cfe8d600-c86f-11eb-9eaa-6fae1865236b.png">

```
❯ curl -I https://maventests.s3.eu-central-1.amazonaws.com/com/automattic/android/publish-library-to-s3/com.automattic.android.publish-library-to-s3.gradle.plugin/0.4.1/com.automattic.android.publish-library-to-s3.gradle.plugin-0.4.1.jar
HTTP/1.1 404 Not Found
x-amz-request-id: B99W20B22DEDBB9Z
x-amz-id-2: NGSVTfjyEyyUUzlzPMNRwm/zKltjb1Y5QaaQ2izCmICKCSODtTm9wFo4+mywerv06iD9qr/jeAY=
Content-Type: application/xml
Date: Tue, 08 Jun 2021 13:40:19 GMT
Server: AmazonS3
```

This will result in just getting `404` during the build process but Gradle will continue to build, which is expected.

Proof that it works can be found on this Automattic-Tracks-Android branch: https://github.com/Automattic/Automattic-Tracks-Android/compare/testing_publish_plugin

---

@oguzkocer WDYT about this? Can we update ACL settings?

**Comment by oguzkocer** [comment]
@wzieba I like this fix, but I am not sure about its implications either. Systems team is the one who controls this bucket and they didn't allow for the CI token to have the list capability (don't know why) so I am not sure what would happen if we were to ask them to open it up to everyone. I'd like @jkmassel to weigh in on this as he is both more experienced in security and if he were to be onboard it'd be more likely to make this happen. (assuming it's OK to do this in the first place)

@jkmassel What do you think?

_P.S: I feel like we shouldn't even use an S3 bucket that's controlled by systems team. We should be able to control the permissions ourselves because it has no implications on any other a8c projects and the projects for the artifacts we host are all open source._

**Comment by wzieba** [comment]
Thank you @oguzkocer for the feedback,

> P.S: I feel like we shouldn't even use an S3 bucket that's controlled by systems team. We should be able to control the permissions ourselves because it has no implications on any other a8c projects and the projects for the artifacts we host are all open source.

Yes, I completely agree - it'd be great to have an independent S3 bucket.

**Comment by jkmassel** [comment]
I think adding public `list` permissions would be just fine – this is effectively just serving a public, static website and everything in this bucket is supposed to be public.

**Comment by oguzkocer** [comment]
This was fixed with a server side change and we have switched several projects to plugin DSL.
