### ISSUE TITLE
Upload sources of the artifacts

### ISSUE THREAD

**Issue by wzieba** [Automattic/publish-to-s3-gradle-plugin#28]
### Challenge I try to address

Artifacts published via `publish-to-s3-gradle-plugin` don't contain a source code which makes them more difficult to work with. If someone working with client code wants to see a source code of used class from a library, they can't do this. See sample below:

| Class from library with not provided sources (FluxC) | Class from library with provided source (Tracks) |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/5845095/133797528-c8bac91e-ab6e-4154-a22c-da9ad9473f51.png) | ![image](https://user-images.githubusercontent.com/5845095/133797694-f91bf5b3-d511-4556-90f2-d174a6d3450e.png) |

As you can see, the second class is readable, just read-only.

### Why to do this?

It makes it easier to work with libraries - sometimes what we need is to just peek a fragment of a source. It's faster to do this in IDE thank looking on Github or opening a separate project.

### How to fix this

I think that if we start to upload sources for artifacts, we'll fix the above issue without any further changes: IDE will take care of merging sources to the .jar/.aar artifact.

Our libraries are open source so it shouldn't be a problematic. If we do have some closed-source libraries we have to remember about not allowing to share sources though.

Naming of the source should follow [convention](https://maven.apache.org/plugin-developers/cookbook/attach-source-javadoc-artifacts.html): `<artifact_name>-sources.jar`.

### Criteria of acceptance

E.g. calling 
```
curl https://a8c-libs.s3.amazonaws.com/android/org/wordpress/fluxc/develop-<recent_hash>/fluxc-develop-<recent_hash>-sources.jar
```

returns a sources instead of `The specified key does not exist.`.

**Comment by oguzkocer** [comment]
Addressed in https://github.com/Automattic/publish-to-s3-gradle-plugin/pull/29.
